[package]
name = "proton-pass-mobile"
edition.workspace = true
version.workspace = true

# Flags for cargo-release
[package.metadata.release]
pre-release-replacements = [
    # Yes, we are relying on the number of whitespaces
    {file="android/lib/build.gradle.kts", search="    version = .*", replace="    version = \"{{version}}\""}
]


[lib]
doctest = false
crate-type = ["cdylib", "staticlib"]
name = "proton_pass_common_mobile"

[features]
default = ["resize-image"]
resize-image = ["proton-pass-common/resize-image"]

[dependencies]
proton-pass-common = { path = "../proton-pass-common", features = ["uniffi", "resize-image"] }
proton-pass-derive = { path = "../proton-pass-derive" }
proton-pass-types = { path = "../proton-pass-types", features = ["uniffi"] }

async-trait.workspace = true
tokio.workspace = true
uniffi.workspace = true
