// WASM Module - will be loaded dynamically
let MarkdownEditor = null;
let editor = null;

// Undo batching - save state after user stops typing or on word boundaries
let undoBatchTimer = null;
const UNDO_BATCH_DELAY = 1000; // 1 second after typing stops

// Function to load the WASM module (ES modules for browser)
async function loadWasmModule() {
    try {
        // Import the ES module generated by wasm-pack with --target web
        const module = await import('./pkg/ui/proton_pass_web.js');
        
        // Initialize the WASM
        await module.default();
        
        // Return the MarkdownEditor class
        return module.MarkdownEditor;
    } catch (error) {
        console.error('Failed to load WASM module:', error);
        throw error;
    }
}

// Helper to get UTF-8 byte length
function utf8ByteLength(str) {
    return new TextEncoder().encode(str).length;
}

// Helper to get cursor position in bytes
function getCursorPositionInBytes(textarea) {
    const text = textarea.value;
    const cursorPos = textarea.selectionStart;
    return utf8ByteLength(text.substring(0, cursorPos));
}

// Helper to convert byte position to string position
function bytePositionToStringPosition(text, bytePos) {
    const encoder = new TextEncoder();
    let stringPos = 0;
    let currentBytes = 0;
    
    while (stringPos < text.length && currentBytes < bytePos) {
        const char = text[stringPos];
        const charBytes = encoder.encode(char).length;
        currentBytes += charBytes;
        stringPos++;
    }
    
    return stringPos;
}

// Schedule saving an undo state after a delay (batching)
function scheduleUndoSave() {
    // Clear existing timer
    if (undoBatchTimer) {
        clearTimeout(undoBatchTimer);
    }

    // Schedule new save
    undoBatchTimer = setTimeout(() => {
        if (editor) {
            editor.saveUndoState();
            updateInfo(); // Update undo/redo button states
        }
    }, UNDO_BATCH_DELAY);
}

// Update editor state
function updateEditor(event) {
    if (!editor) return;

    const textarea = document.getElementById('editor');
    const text = textarea.value;

    // Sync text to editor (does NOT save undo state)
    editor.setText(text);

    // Sync cursor position
    try {
        const cursorBytes = getCursorPositionInBytes(textarea);
        editor.setCursor(cursorBytes);

        // Check if there's a selection
        if (textarea.selectionStart !== textarea.selectionEnd) {
            const startBytes = utf8ByteLength(text.substring(0, textarea.selectionStart));
            const endBytes = utf8ByteLength(text.substring(0, textarea.selectionEnd));
            editor.setSelection(startBytes, endBytes);
        }
    } catch (e) {
        console.warn('Failed to update cursor:', e);
    }

    updatePreview();
    updateInfo();

    // Smart undo batching: save state on word boundaries or after delay
    if (event && event.type === 'input') {
        const lastChar = event.data;

        // Save immediately on space (end of word) or newline
        if (lastChar === ' ' || lastChar === '\n' || lastChar === '\t') {
            if (undoBatchTimer) {
                clearTimeout(undoBatchTimer);
                undoBatchTimer = null;
            }
            editor.saveUndoState();
            updateInfo();
        } else {
            // Schedule save after typing stops
            scheduleUndoSave();
        }
    }
}

// Update preview
function updatePreview() {
    if (!editor) return;

    const previewDiv = document.getElementById('preview');
    const rawHtmlDiv = document.getElementById('raw-html');
    const markdownDisplay = document.getElementById('markdown-display');

    // Render HTML
    const html = editor.renderToHtml();
    previewDiv.innerHTML = html;
    rawHtmlDiv.textContent = html;

    // Show markdown with styling
    const text = editor.getText();
    markdownDisplay.textContent = text || 'Raw markdown will appear here...';

    // Update styled overlay for hybrid mode
    updateStyledOverlay();

    // Update spans display
    updateSpansDisplay();
}

// Update the styled overlay with hybrid mode rendering
function updateStyledOverlay() {
    if (!editor) return;

    const overlay = document.getElementById('styled-overlay');
    const text = editor.getText();
    const spans = editor.render();

    if (!text) {
        overlay.innerHTML = '';
        return;
    }

    // NOTE: Rust library now returns UTF-16 offsets directly, which match JavaScript's string indexing!
    // No conversion needed - we can use span.start and span.end directly as string indices.

    // Build a character-level style map
    const charStyles = new Array(text.length).fill(null).map(() => new Set());

    // First pass: collect all styles for each character (offsets are already UTF-16)
    spans.forEach(span => {
        const charStart = Math.min(span.start, text.length);
        const charEnd = Math.min(span.end, text.length);

        for (let i = charStart; i < charEnd; i++) {
            charStyles[i].add(span.style);
        }
    });

    // Build HTML with proper style priority (markers override content)
    let html = '';
    let currentClasses = new Set();

    for (let i = 0; i < text.length; i++) {
        const styles = charStyles[i];
        const newClasses = new Set();

        // Check if this character is a marker - if so, ONLY apply marker style
        if (styles.has('markdownMarker')) {
            newClasses.add('md-marker');
        } else {
            // Not a marker, apply content styles
            styles.forEach(style => {
                const className = getStyleClass(style);
                if (className) {
                    newClasses.add(className);
                }
            });
        }

        // Check if we need to close/open spans
        const classesChanged = !setsEqual(currentClasses, newClasses);

        if (classesChanged) {
            // Close previous spans
            if (currentClasses.size > 0) {
                html += '</span>';
            }

            // Open new spans
            if (newClasses.size > 0) {
                const classList = Array.from(newClasses).join(' ');
                html += `<span class="${classList}">`;
            }

            currentClasses = newClasses;
        }

        // Add the character (escape HTML)
        html += escapeHtml(text[i]);
    }

    // Close any remaining spans
    if (currentClasses.size > 0) {
        html += '</span>';
    }

    overlay.innerHTML = html;
}

// Helper: Convert span style to CSS class
function getStyleClass(style) {
    const styleMap = {
        'bold': 'md-bold',
        'italic': 'md-italic',
        'strikethrough': 'md-strikethrough',
        'header1': 'md-header',
        'header2': 'md-header',
        'header3': 'md-header',
        'header4': 'md-header',
        'header5': 'md-header',
        'header6': 'md-header',
        'code': 'md-code',
        'link': 'md-link',
        'orderedListItem': 'md-list',
        'unorderedListItem': 'md-list',
        'blockquote': 'md-blockquote',
        'markdownMarker': 'md-marker',
    };
    return styleMap[style] || '';
}

// Helper: Compare two sets
function setsEqual(a, b) {
    if (a.size !== b.size) return false;
    for (let item of a) {
        if (!b.has(item)) return false;
    }
    return true;
}

// Helper: Escape HTML
function escapeHtml(text) {
    const div = document.createElement('div');
    div.textContent = text;
    return div.innerHTML;
}

// Update info panel
function updateInfo() {
    if (!editor) return;
    
    const textarea = document.getElementById('editor');
    const text = editor.getText();
    
    // Character count
    document.getElementById('char-count').textContent = text.length;
    
    // Word count
    const words = text.trim().split(/\s+/).filter(w => w.length > 0).length;
    document.getElementById('word-count').textContent = words;
    
    // Selection info
    const selStart = textarea.selectionStart;
    const selEnd = textarea.selectionEnd;
    if (selStart === selEnd) {
        document.getElementById('selection-info').textContent = 'None';
    } else {
        document.getElementById('selection-info').textContent = `${selEnd - selStart} chars`;
    }
    
    // Undo/redo info
    const canUndo = editor.canUndo();
    const canRedo = editor.canRedo();
    document.getElementById('undo-info').textContent = `${canUndo ? '✓' : '✗'} / ${canRedo ? '✓' : '✗'}`;
    
    // Update buttons
    document.getElementById('btn-undo').disabled = !canUndo;
    document.getElementById('btn-redo').disabled = !canRedo;
    
    // Update cursor info
    updateCursorInfo();
}

// Update cursor info
function updateCursorInfo() {
    const textarea = document.getElementById('editor');
    const text = textarea.value;
    const cursorPos = textarea.selectionStart;
    
    // Calculate line and column
    const lines = text.substring(0, cursorPos).split('\n');
    const line = lines.length;
    const col = lines[lines.length - 1].length + 1;
    
    document.getElementById('cursor-info').textContent = `Line ${line}, Col ${col}`;
}

// Update spans display
function updateSpansDisplay() {
    if (!editor) return;
    
    const container = document.getElementById('spans-container');
    const spans = editor.render();
    
    if (spans.length === 0) {
        container.innerHTML = '<p class="empty-state">No styled content yet</p>';
        return;
    }
    
    const text = editor.getText();
    container.innerHTML = '';
    
    spans.forEach(span => {
        const div = document.createElement('div');
        div.className = 'span-item';
        
        const styleSpan = document.createElement('span');
        styleSpan.className = `span-style ${span.style}`;
        styleSpan.textContent = span.style;
        
        const rangeSpan = document.createElement('span');
        rangeSpan.className = 'span-range';
        rangeSpan.textContent = `[${span.start}:${span.end}]`;
        
        const textSpan = document.createElement('span');
        textSpan.className = 'span-text';
        const spanText = text.substring(span.start, Math.min(span.end, text.length));
        textSpan.textContent = `"${spanText.substring(0, 50)}${spanText.length > 50 ? '...' : ''}"`;
        
        div.appendChild(styleSpan);
        div.appendChild(rangeSpan);
        div.appendChild(textSpan);
        
        if (span.url) {
            const urlSpan = document.createElement('span');
            urlSpan.className = 'span-range';
            urlSpan.textContent = ` → ${span.url}`;
            div.appendChild(urlSpan);
        }
        
        container.appendChild(div);
    });
}

// Apply operation
function applyOperation(operation) {
    if (!editor) return;
    
    const textarea = document.getElementById('editor');
    
    try {
        // Set selection in editor
        const startBytes = utf8ByteLength(textarea.value.substring(0, textarea.selectionStart));
        const endBytes = utf8ByteLength(textarea.value.substring(0, textarea.selectionEnd));
        
        if (startBytes !== endBytes) {
            editor.setSelection(startBytes, endBytes);
        } else {
            editor.setCursor(startBytes);
        }
        
        // Apply operation
        editor.applyOperation(operation);
        
        // Update textarea
        const newText = editor.getText();
        textarea.value = newText;
        
        // Set cursor position
        const newCursorBytes = editor.getCursor();
        const newCursorPos = bytePositionToStringPosition(newText, newCursorBytes);
        textarea.selectionStart = newCursorPos;
        textarea.selectionEnd = newCursorPos;
        
        textarea.focus();
        
        updatePreview();
        updateInfo();
    } catch (error) {
        showError(error.message);
    }
}

// Show error
function showError(message) {
    const errorDiv = document.getElementById('error-message');
    const errorText = document.getElementById('error-text');
    errorText.textContent = message;
    errorDiv.style.display = 'block';
    
    setTimeout(() => {
        errorDiv.style.display = 'none';
    }, 5000);
}

// Initialize
async function init() {
    try {
        // Load WASM module and get the MarkdownEditor class
        MarkdownEditor = await loadWasmModule();
        
        // Create editor with initial content
        editor = new MarkdownEditor('# Welcome to Proton Pass Markdown Editor!\n\nStart editing to see the magic happen. ✨\n\n## Features\n\n- **Bold** text\n- *Italic* text\n- ~~Strikethrough~~ text\n- Headers (H1-H6)\n- Blockquotes\n- Lists (ordered and unordered)\n- Full undo/redo support\n\n> This is a blockquote! Click the ❝ Quote button to toggle blockquotes on any line.\n\n## Try it out!\n\nSelect some text and click the formatting buttons above.');
        
        // Set initial content in textarea
        const textarea = document.getElementById('editor');
        textarea.value = editor.getText();
        
        // Update preview
        updatePreview();
        updateInfo();
        
        // Hide loading
        document.getElementById('loading').style.display = 'none';
        
        // Setup event listeners
        setupEventListeners();
        
    } catch (error) {
        console.error('Failed to initialize:', error);
        document.getElementById('loading').innerHTML = `
            <div style="text-align: center; color: #ff4444;">
                <h2>❌ Failed to Load</h2>
                <p>${error.message}</p>
                <p style="margin-top: 20px; color: #b0b0b0;">Make sure you've built the WASM module:</p>
                <pre style="background: #2a2a2a; padding: 15px; border-radius: 6px; display: inline-block; text-align: left; margin-top: 10px;">
cd test-markdown-website
./setup.sh</pre>
            </div>
        `;
    }
}

// Setup event listeners
function setupEventListeners() {
    const textarea = document.getElementById('editor');
    const overlay = document.getElementById('styled-overlay');

    // Editor events - update immediately on any change
    textarea.addEventListener('input', updateEditor);
    textarea.addEventListener('paste', () => setTimeout(updateEditor, 0));
    textarea.addEventListener('cut', () => setTimeout(updateEditor, 0));
    textarea.addEventListener('selectionchange', updateInfo);
    textarea.addEventListener('keyup', updateCursorInfo);
    textarea.addEventListener('mouseup', updateCursorInfo);

    // Sync scroll between textarea and overlay
    textarea.addEventListener('scroll', () => {
        overlay.scrollTop = textarea.scrollTop;
        overlay.scrollLeft = textarea.scrollLeft;
    });

    // Keyboard shortcuts + immediate updates for certain keys
    textarea.addEventListener('keydown', (e) => {
        // Handle Enter key for smart list continuation
        if (e.key === 'Enter' && !e.shiftKey && !e.ctrlKey && !e.metaKey) {
            e.preventDefault();

            try {
                // Use smart newline insertion from Rust
                editor.insertNewline();

                // Sync the text and cursor back to textarea
                const newText = editor.getText();
                const cursorPos = editor.getCursor();  // Now returns UTF-16 offset directly

                textarea.value = newText;

                // Rust library now returns UTF-16 offsets (which JS uses natively)
                textarea.setSelectionRange(cursorPos, cursorPos);

                // Update displays
                updatePreview();
                updateInfo();
            } catch (e) {
                console.error('Failed to insert newline:', e);
                // Fallback: let default behavior happen
                textarea.value = textarea.value.substring(0, textarea.selectionStart) + '\n' +
                                 textarea.value.substring(textarea.selectionEnd);
                textarea.selectionStart = textarea.selectionEnd = textarea.selectionStart + 1;
            }
            return;
        }

        // Handle keyboard shortcuts
        if (e.ctrlKey || e.metaKey) {
            switch (e.key.toLowerCase()) {
                case 'b':
                    e.preventDefault();
                    applyOperation('bold');
                    break;
                case 'i':
                    e.preventDefault();
                    applyOperation('italic');
                    break;
                case 'z':
                    if (e.shiftKey) {
                        e.preventDefault();
                        handleRedo();
                    } else {
                        e.preventDefault();
                        handleUndo();
                    }
                    break;
                case 'y':
                    e.preventDefault();
                    handleRedo();
                    break;
            }
        }
    });
    
    // Toolbar buttons
    document.getElementById('btn-bold').addEventListener('click', () => applyOperation('bold'));
    document.getElementById('btn-italic').addEventListener('click', () => applyOperation('italic'));
    document.getElementById('btn-strikethrough').addEventListener('click', () => applyOperation('strikethrough'));
    document.getElementById('btn-h1').addEventListener('click', () => applyOperation('header1'));
    document.getElementById('btn-h2').addEventListener('click', () => applyOperation('header2'));
    document.getElementById('btn-h3').addEventListener('click', () => applyOperation('header3'));
    document.getElementById('btn-blockquote').addEventListener('click', () => applyOperation('blockquote'));
    document.getElementById('btn-ul').addEventListener('click', () => applyOperation('createUnorderedList'));
    document.getElementById('btn-ol').addEventListener('click', () => applyOperation('createOrderedList'));
    document.getElementById('btn-indent').addEventListener('click', () => applyOperation('indentList'));
    document.getElementById('btn-unindent').addEventListener('click', () => applyOperation('unindentList'));
    document.getElementById('btn-undo').addEventListener('click', handleUndo);
    document.getElementById('btn-redo').addEventListener('click', handleRedo);
    document.getElementById('btn-clear').addEventListener('click', handleClear);
    
    // Toggle view
    document.getElementById('toggle-view').addEventListener('change', (e) => {
        const preview = document.getElementById('preview');
        const rawHtml = document.getElementById('raw-html');
        
        if (e.target.checked) {
            preview.classList.add('active');
            rawHtml.classList.remove('active');
        } else {
            preview.classList.remove('active');
            rawHtml.classList.add('active');
        }
    });
}

// Handle undo
function handleUndo() {
    if (!editor || !editor.canUndo()) return;
    
    editor.undo();
    
    const textarea = document.getElementById('editor');
    textarea.value = editor.getText();
    
    // Update cursor
    const cursorBytes = editor.getCursor();
    const cursorPos = bytePositionToStringPosition(textarea.value, cursorBytes);
    textarea.selectionStart = cursorPos;
    textarea.selectionEnd = cursorPos;
    
    textarea.focus();
    updatePreview();
    updateInfo();
}

// Handle redo
function handleRedo() {
    if (!editor || !editor.canRedo()) return;
    
    editor.redo();
    
    const textarea = document.getElementById('editor');
    textarea.value = editor.getText();
    
    // Update cursor
    const cursorBytes = editor.getCursor();
    const cursorPos = bytePositionToStringPosition(textarea.value, cursorBytes);
    textarea.selectionStart = cursorPos;
    textarea.selectionEnd = cursorPos;
    
    textarea.focus();
    updatePreview();
    updateInfo();
}

// Handle clear
function handleClear() {
    if (!confirm('Are you sure you want to clear all content?')) return;
    
    if (!editor) return;
    
    editor.setText('');
    
    const textarea = document.getElementById('editor');
    textarea.value = '';
    textarea.focus();
    
    updatePreview();
    updateInfo();
}

// Initialize on load
window.addEventListener('DOMContentLoaded', init);

