// WASM Module - will be loaded dynamically
let MarkdownEditor = null;
let editor = null;

// Function to load the WASM module (ES modules for browser)
async function loadWasmModule() {
    try {
        // Import the ES module generated by wasm-pack with --target web
        const module = await import('./pkg/ui/proton_pass_web.js');
        
        // Initialize the WASM
        await module.default();
        
        // Return the MarkdownEditor class
        return module.MarkdownEditor;
    } catch (error) {
        console.error('Failed to load WASM module:', error);
        throw error;
    }
}

// Helper to get UTF-8 byte length
function utf8ByteLength(str) {
    return new TextEncoder().encode(str).length;
}

// Helper to get cursor position in bytes
function getCursorPositionInBytes(textarea) {
    const text = textarea.value;
    const cursorPos = textarea.selectionStart;
    return utf8ByteLength(text.substring(0, cursorPos));
}

// Helper to convert byte position to string position
function bytePositionToStringPosition(text, bytePos) {
    const encoder = new TextEncoder();
    let stringPos = 0;
    let currentBytes = 0;
    
    while (stringPos < text.length && currentBytes < bytePos) {
        const char = text[stringPos];
        const charBytes = encoder.encode(char).length;
        currentBytes += charBytes;
        stringPos++;
    }
    
    return stringPos;
}

// Update editor state
function updateEditor() {
    if (!editor) return;
    
    const textarea = document.getElementById('editor');
    const text = textarea.value;
    
    // Sync text to editor
    editor.setText(text);
    
    // Sync cursor position
    try {
        const cursorBytes = getCursorPositionInBytes(textarea);
        editor.setCursor(cursorBytes);
        
        // Check if there's a selection
        if (textarea.selectionStart !== textarea.selectionEnd) {
            const startBytes = utf8ByteLength(text.substring(0, textarea.selectionStart));
            const endBytes = utf8ByteLength(text.substring(0, textarea.selectionEnd));
            editor.setSelection(startBytes, endBytes);
        }
    } catch (e) {
        console.warn('Failed to update cursor:', e);
    }
    
    updatePreview();
    updateInfo();
}

// Update preview
function updatePreview() {
    if (!editor) return;
    
    const previewDiv = document.getElementById('preview');
    const rawHtmlDiv = document.getElementById('raw-html');
    const markdownDisplay = document.getElementById('markdown-display');
    
    // Render HTML
    const html = editor.renderToHtml();
    previewDiv.innerHTML = html;
    rawHtmlDiv.textContent = html;
    
    // Show markdown with styling
    const text = editor.getText();
    markdownDisplay.textContent = text || 'Raw markdown will appear here...';
    
    // Update spans display
    updateSpansDisplay();
}

// Update info panel
function updateInfo() {
    if (!editor) return;
    
    const textarea = document.getElementById('editor');
    const text = editor.getText();
    
    // Character count
    document.getElementById('char-count').textContent = text.length;
    
    // Word count
    const words = text.trim().split(/\s+/).filter(w => w.length > 0).length;
    document.getElementById('word-count').textContent = words;
    
    // Selection info
    const selStart = textarea.selectionStart;
    const selEnd = textarea.selectionEnd;
    if (selStart === selEnd) {
        document.getElementById('selection-info').textContent = 'None';
    } else {
        document.getElementById('selection-info').textContent = `${selEnd - selStart} chars`;
    }
    
    // Undo/redo info
    const canUndo = editor.canUndo();
    const canRedo = editor.canRedo();
    document.getElementById('undo-info').textContent = `${canUndo ? '✓' : '✗'} / ${canRedo ? '✓' : '✗'}`;
    
    // Update buttons
    document.getElementById('btn-undo').disabled = !canUndo;
    document.getElementById('btn-redo').disabled = !canRedo;
    
    // Update cursor info
    updateCursorInfo();
}

// Update cursor info
function updateCursorInfo() {
    const textarea = document.getElementById('editor');
    const text = textarea.value;
    const cursorPos = textarea.selectionStart;
    
    // Calculate line and column
    const lines = text.substring(0, cursorPos).split('\n');
    const line = lines.length;
    const col = lines[lines.length - 1].length + 1;
    
    document.getElementById('cursor-info').textContent = `Line ${line}, Col ${col}`;
}

// Update spans display
function updateSpansDisplay() {
    if (!editor) return;
    
    const container = document.getElementById('spans-container');
    const spans = editor.render();
    
    if (spans.length === 0) {
        container.innerHTML = '<p class="empty-state">No styled content yet</p>';
        return;
    }
    
    const text = editor.getText();
    container.innerHTML = '';
    
    spans.forEach(span => {
        const div = document.createElement('div');
        div.className = 'span-item';
        
        const styleSpan = document.createElement('span');
        styleSpan.className = `span-style ${span.style}`;
        styleSpan.textContent = span.style;
        
        const rangeSpan = document.createElement('span');
        rangeSpan.className = 'span-range';
        rangeSpan.textContent = `[${span.start}:${span.end}]`;
        
        const textSpan = document.createElement('span');
        textSpan.className = 'span-text';
        const spanText = text.substring(span.start, Math.min(span.end, text.length));
        textSpan.textContent = `"${spanText.substring(0, 50)}${spanText.length > 50 ? '...' : ''}"`;
        
        div.appendChild(styleSpan);
        div.appendChild(rangeSpan);
        div.appendChild(textSpan);
        
        if (span.url) {
            const urlSpan = document.createElement('span');
            urlSpan.className = 'span-range';
            urlSpan.textContent = ` → ${span.url}`;
            div.appendChild(urlSpan);
        }
        
        container.appendChild(div);
    });
}

// Apply operation
function applyOperation(operation) {
    if (!editor) return;
    
    const textarea = document.getElementById('editor');
    
    try {
        // Set selection in editor
        const startBytes = utf8ByteLength(textarea.value.substring(0, textarea.selectionStart));
        const endBytes = utf8ByteLength(textarea.value.substring(0, textarea.selectionEnd));
        
        if (startBytes !== endBytes) {
            editor.setSelection(startBytes, endBytes);
        } else {
            editor.setCursor(startBytes);
        }
        
        // Apply operation
        editor.applyOperation(operation);
        
        // Update textarea
        const newText = editor.getText();
        textarea.value = newText;
        
        // Set cursor position
        const newCursorBytes = editor.getCursor();
        const newCursorPos = bytePositionToStringPosition(newText, newCursorBytes);
        textarea.selectionStart = newCursorPos;
        textarea.selectionEnd = newCursorPos;
        
        textarea.focus();
        
        updatePreview();
        updateInfo();
    } catch (error) {
        showError(error.message);
    }
}

// Show error
function showError(message) {
    const errorDiv = document.getElementById('error-message');
    const errorText = document.getElementById('error-text');
    errorText.textContent = message;
    errorDiv.style.display = 'block';
    
    setTimeout(() => {
        errorDiv.style.display = 'none';
    }, 5000);
}

// Initialize
async function init() {
    try {
        // Load WASM module and get the MarkdownEditor class
        MarkdownEditor = await loadWasmModule();
        
        // Create editor with initial content
        editor = new MarkdownEditor('# Welcome to Proton Pass Markdown Editor!\n\nStart editing to see the magic happen. ✨\n\n## Features\n\n- **Bold** text\n- *Italic* text\n- ~~Strikethrough~~ text\n- Headers (H1-H6)\n- Blockquotes\n- Lists (ordered and unordered)\n- Full undo/redo support\n\n> This is a blockquote! Click the ❝ Quote button to toggle blockquotes on any line.\n\n## Try it out!\n\nSelect some text and click the formatting buttons above.');
        
        // Set initial content in textarea
        const textarea = document.getElementById('editor');
        textarea.value = editor.getText();
        
        // Update preview
        updatePreview();
        updateInfo();
        
        // Hide loading
        document.getElementById('loading').style.display = 'none';
        
        // Setup event listeners
        setupEventListeners();
        
    } catch (error) {
        console.error('Failed to initialize:', error);
        document.getElementById('loading').innerHTML = `
            <div style="text-align: center; color: #ff4444;">
                <h2>❌ Failed to Load</h2>
                <p>${error.message}</p>
                <p style="margin-top: 20px; color: #b0b0b0;">Make sure you've built the WASM module:</p>
                <pre style="background: #2a2a2a; padding: 15px; border-radius: 6px; display: inline-block; text-align: left; margin-top: 10px;">
cd test-markdown-website
./setup.sh</pre>
            </div>
        `;
    }
}

// Setup event listeners
function setupEventListeners() {
    const textarea = document.getElementById('editor');
    
    // Editor events
    textarea.addEventListener('input', updateEditor);
    textarea.addEventListener('selectionchange', updateInfo);
    textarea.addEventListener('keyup', updateCursorInfo);
    textarea.addEventListener('mouseup', updateCursorInfo);
    
    // Keyboard shortcuts
    textarea.addEventListener('keydown', (e) => {
        if (e.ctrlKey || e.metaKey) {
            switch (e.key.toLowerCase()) {
                case 'b':
                    e.preventDefault();
                    applyOperation('bold');
                    break;
                case 'i':
                    e.preventDefault();
                    applyOperation('italic');
                    break;
                case 'z':
                    if (e.shiftKey) {
                        e.preventDefault();
                        handleRedo();
                    } else {
                        e.preventDefault();
                        handleUndo();
                    }
                    break;
                case 'y':
                    e.preventDefault();
                    handleRedo();
                    break;
            }
        }
    });
    
    // Toolbar buttons
    document.getElementById('btn-bold').addEventListener('click', () => applyOperation('bold'));
    document.getElementById('btn-italic').addEventListener('click', () => applyOperation('italic'));
    document.getElementById('btn-strikethrough').addEventListener('click', () => applyOperation('strikethrough'));
    document.getElementById('btn-h1').addEventListener('click', () => applyOperation('header1'));
    document.getElementById('btn-h2').addEventListener('click', () => applyOperation('header2'));
    document.getElementById('btn-h3').addEventListener('click', () => applyOperation('header3'));
    document.getElementById('btn-blockquote').addEventListener('click', () => applyOperation('blockquote'));
    document.getElementById('btn-ul').addEventListener('click', () => applyOperation('createUnorderedList'));
    document.getElementById('btn-ol').addEventListener('click', () => applyOperation('createOrderedList'));
    document.getElementById('btn-indent').addEventListener('click', () => applyOperation('indentList'));
    document.getElementById('btn-unindent').addEventListener('click', () => applyOperation('unindentList'));
    document.getElementById('btn-undo').addEventListener('click', handleUndo);
    document.getElementById('btn-redo').addEventListener('click', handleRedo);
    document.getElementById('btn-clear').addEventListener('click', handleClear);
    
    // Toggle view
    document.getElementById('toggle-view').addEventListener('change', (e) => {
        const preview = document.getElementById('preview');
        const rawHtml = document.getElementById('raw-html');
        
        if (e.target.checked) {
            preview.classList.add('active');
            rawHtml.classList.remove('active');
        } else {
            preview.classList.remove('active');
            rawHtml.classList.add('active');
        }
    });
}

// Handle undo
function handleUndo() {
    if (!editor || !editor.canUndo()) return;
    
    editor.undo();
    
    const textarea = document.getElementById('editor');
    textarea.value = editor.getText();
    
    // Update cursor
    const cursorBytes = editor.getCursor();
    const cursorPos = bytePositionToStringPosition(textarea.value, cursorBytes);
    textarea.selectionStart = cursorPos;
    textarea.selectionEnd = cursorPos;
    
    textarea.focus();
    updatePreview();
    updateInfo();
}

// Handle redo
function handleRedo() {
    if (!editor || !editor.canRedo()) return;
    
    editor.redo();
    
    const textarea = document.getElementById('editor');
    textarea.value = editor.getText();
    
    // Update cursor
    const cursorBytes = editor.getCursor();
    const cursorPos = bytePositionToStringPosition(textarea.value, cursorBytes);
    textarea.selectionStart = cursorPos;
    textarea.selectionEnd = cursorPos;
    
    textarea.focus();
    updatePreview();
    updateInfo();
}

// Handle clear
function handleClear() {
    if (!confirm('Are you sure you want to clear all content?')) return;
    
    if (!editor) return;
    
    editor.setText('');
    
    const textarea = document.getElementById('editor');
    textarea.value = '';
    textarea.focus();
    
    updatePreview();
    updateInfo();
}

// Initialize on load
window.addEventListener('DOMContentLoaded', init);

