// WASM Module - will be loaded dynamically
let MarkdownEditor = null;
let parseMarkdownDocument = null;
let editor = null;

// Undo batching - save state after user stops typing or on word boundaries
let undoBatchTimer = null;
const UNDO_BATCH_DELAY = 1000; // 1 second after typing stops

// Function to load the WASM module (ES modules for browser)
async function loadWasmModule() {
    try {
        // Import the ES module generated by wasm-pack with --target web
        const module = await import('./pkg/ui/proton_pass_web.js');
        
        // Initialize the WASM
        await module.default();
        
        return {
            MarkdownEditor: module.MarkdownEditor,
            parseMarkdownDocument: module.parseMarkdownDocument,
        };
    } catch (error) {
        console.error('Failed to load WASM module:', error);
        throw error;
    }
}

// Helper to get UTF-8 byte length
function utf8ByteLength(str) {
    return new TextEncoder().encode(str).length;
}

// Helper to get cursor position in bytes
function getCursorPositionInBytes(textarea) {
    const text = textarea.value;
    const cursorPos = textarea.selectionStart;
    return utf8ByteLength(text.substring(0, cursorPos));
}

// Helper to convert byte position to string position
function bytePositionToStringPosition(text, bytePos) {
    const encoder = new TextEncoder();
    let stringPos = 0;
    let currentBytes = 0;
    
    while (stringPos < text.length && currentBytes < bytePos) {
        const char = text[stringPos];
        const charBytes = encoder.encode(char).length;
        currentBytes += charBytes;
        stringPos++;
    }
    
    return stringPos;
}

// Schedule saving an undo state after a delay (batching)
function scheduleUndoSave() {
    // Clear existing timer
    if (undoBatchTimer) {
        clearTimeout(undoBatchTimer);
    }

    // Schedule new save
    undoBatchTimer = setTimeout(() => {
        if (editor) {
            editor.saveUndoState();
            updateInfo(); // Update undo/redo button states
        }
    }, UNDO_BATCH_DELAY);
}

// Update editor state
function updateEditor(event) {
    if (!editor) return;

    const textarea = document.getElementById('editor');
    const text = textarea.value;

    // Sync text to editor (does NOT save undo state)
    editor.setText(text);

    // Sync cursor position
    // NOTE: Rust library now uses UTF-16 offsets, which match JavaScript's native string indexing
    // So we can use selectionStart/selectionEnd directly without conversion!
    try {
        // Check if there's a selection
        if (textarea.selectionStart !== textarea.selectionEnd) {
            editor.setSelection(textarea.selectionStart, textarea.selectionEnd);
        } else {
            editor.setCursor(textarea.selectionStart);
        }
    } catch (e) {
        console.warn('Failed to update cursor:', e);
    }

    updatePreview();
    updateInfo();

    // Smart undo batching: save state on word boundaries or after delay
    if (event && event.type === 'input') {
        const lastChar = event.data;

        // Save immediately on space (end of word) or newline
        if (lastChar === ' ' || lastChar === '\n' || lastChar === '\t') {
            if (undoBatchTimer) {
                clearTimeout(undoBatchTimer);
                undoBatchTimer = null;
            }
            editor.saveUndoState();
            updateInfo();
        } else {
            // Schedule save after typing stops
            scheduleUndoSave();
        }
    }
}

// Update preview
function updatePreview() {
    if (!editor) return;

    const previewDiv = document.getElementById('preview');
    const rawHtmlDiv = document.getElementById('raw-html');
    const markdownDisplay = document.getElementById('markdown-display');

    const markdownDocument = parseMarkdownDocument(editor.getText());
    renderMarkdownDocument(previewDiv, markdownDocument);
    rawHtmlDiv.textContent = JSON.stringify(markdownDocument, null, 2);

    // Show markdown with styling
    const text = editor.getText();
    markdownDisplay.textContent = text || 'Raw markdown will appear here...';

    // Update styled overlay for hybrid mode
    updateStyledOverlay();

    // Update spans display
    updateSpansDisplay();
}

// Update the styled overlay with hybrid mode rendering
function updateStyledOverlay() {
    if (!editor) return;

    const overlay = document.getElementById('styled-overlay');
    const text = editor.getText();
    const spans = editor.renderEditorSpans();

    if (!text) {
        overlay.replaceChildren();
        return;
    }

    // NOTE: Rust library now returns UTF-16 offsets directly, which match JavaScript's string indexing!
    // No conversion needed - we can use span.start and span.end directly as string indices.

    overlay.replaceChildren();

    // Build a character-level style map
    const charStyles = new Array(text.length).fill(null).map(() => new Set());

    // First pass: collect all styles for each character (offsets are already UTF-16)
    spans.forEach(span => {
        const charStart = Math.min(span.start, text.length);
        const charEnd = Math.min(span.end, text.length);

        for (let i = charStart; i < charEnd; i++) {
            charStyles[i].add(span.style);
        }
    });

    // Build DOM with proper style priority (markers override content)
    let currentClasses = new Set();
    let activeSpan = null;

    for (let i = 0; i < text.length; i++) {
        const styles = charStyles[i];
        const newClasses = new Set();

        // Check if this character is a marker - if so, ONLY apply marker style
        if (styles.has('markdownMarker')) {
            newClasses.add('md-marker');
        } else {
            // Not a marker, apply content styles
            styles.forEach(style => {
                const className = getStyleClass(style);
                if (className) {
                    newClasses.add(className);
                }
            });
        }

        // Check if we need to close/open spans
        const classesChanged = !setsEqual(currentClasses, newClasses);

        if (classesChanged) {
            if (newClasses.size > 0) {
                activeSpan = document.createElement('span');
                const classList = Array.from(newClasses).join(' ');
                activeSpan.className = classList;
                overlay.appendChild(activeSpan);
            } else {
                activeSpan = null;
            }

            currentClasses = newClasses;
        }

        const textNode = document.createTextNode(text[i]);
        if (activeSpan) {
            activeSpan.appendChild(textNode);
        } else {
            overlay.appendChild(textNode);
        }
    }
}

// Helper: Convert span style to CSS class
function getStyleClass(style) {
    const styleMap = {
        'bold': 'md-bold',
        'italic': 'md-italic',
        'strikethrough': 'md-strikethrough',
        'header1': 'md-header',
        'header2': 'md-header',
        'header3': 'md-header',
        'header4': 'md-header',
        'header5': 'md-header',
        'header6': 'md-header',
        'code': 'md-code',
        'link': 'md-link',
        'orderedListItem': 'md-list',
        'unorderedListItem': 'md-list',
        'blockquote': 'md-blockquote',
        'markdownMarker': 'md-marker',
    };
    return styleMap[style] || '';
}

// Helper: Compare two sets
function setsEqual(a, b) {
    if (a.size !== b.size) return false;
    for (let item of a) {
        if (!b.has(item)) return false;
    }
    return true;
}

// Update info panel
function updateInfo() {
    if (!editor) return;
    
    const textarea = document.getElementById('editor');
    const text = editor.getText();
    
    // Character count
    document.getElementById('char-count').textContent = text.length;
    
    // Word count
    const words = text.trim().split(/\s+/).filter(w => w.length > 0).length;
    document.getElementById('word-count').textContent = words;
    
    // Selection info
    const selStart = textarea.selectionStart;
    const selEnd = textarea.selectionEnd;
    if (selStart === selEnd) {
        document.getElementById('selection-info').textContent = 'None';
    } else {
        document.getElementById('selection-info').textContent = `${selEnd - selStart} chars`;
    }
    
    // Undo/redo info
    const canUndo = editor.canUndo();
    const canRedo = editor.canRedo();
    document.getElementById('undo-info').textContent = `${canUndo ? '✓' : '✗'} / ${canRedo ? '✓' : '✗'}`;
    
    // Update buttons
    document.getElementById('btn-undo').disabled = !canUndo;
    document.getElementById('btn-redo').disabled = !canRedo;
    
    // Update cursor info
    updateCursorInfo();
}

// Update cursor info
function updateCursorInfo() {
    const textarea = document.getElementById('editor');
    const text = textarea.value;
    const cursorPos = textarea.selectionStart;
    
    // Calculate line and column
    const lines = text.substring(0, cursorPos).split('\n');
    const line = lines.length;
    const col = lines[lines.length - 1].length + 1;
    
    document.getElementById('cursor-info').textContent = `Line ${line}, Col ${col}`;
}

// Update spans display
function updateSpansDisplay() {
    if (!editor) return;
    
    const container = document.getElementById('spans-container');
    const spans = editor.renderEditorSpans();
    
    if (spans.length === 0) {
        const emptyState = document.createElement('p');
        emptyState.className = 'empty-state';
        emptyState.textContent = 'No styled content yet';
        container.replaceChildren(emptyState);
        return;
    }
    
    const text = editor.getText();
    container.replaceChildren();
    
    spans.forEach(span => {
        const div = document.createElement('div');
        div.className = 'span-item';
        
        const styleSpan = document.createElement('span');
        styleSpan.className = `span-style ${span.style}`;
        styleSpan.textContent = span.style;
        
        const rangeSpan = document.createElement('span');
        rangeSpan.className = 'span-range';
        rangeSpan.textContent = `[${span.start}:${span.end}]`;
        
        const textSpan = document.createElement('span');
        textSpan.className = 'span-text';
        const spanText = text.substring(span.start, Math.min(span.end, text.length));
        textSpan.textContent = `"${spanText.substring(0, 50)}${spanText.length > 50 ? '...' : ''}"`;
        
        div.appendChild(styleSpan);
        div.appendChild(rangeSpan);
        div.appendChild(textSpan);
        
        if (span.url) {
            const urlSpan = document.createElement('span');
            urlSpan.className = 'span-range';
            urlSpan.textContent = ` → ${span.url}`;
            div.appendChild(urlSpan);
        }
        
        container.appendChild(div);
    });
}

// Apply operation
function applyOperation(operation) {
    if (!editor) return;

    const textarea = document.getElementById('editor');

    try {
        // Set selection in editor
        // NOTE: Rust library now uses UTF-16 offsets, which match JavaScript's native string indexing
        // So we can use selectionStart/selectionEnd directly without conversion!
        const start = textarea.selectionStart;
        const end = textarea.selectionEnd;

        if (start !== end) {
            editor.setSelection(start, end);
        } else {
            editor.setCursor(start);
        }

        // Apply operation
        editor.applyOperation(operation);

        // Update textarea
        const newText = editor.getText();
        textarea.value = newText;

        // Set cursor position
        // Rust library returns UTF-16 offset directly, no conversion needed
        const newCursorPos = editor.getCursor();
        textarea.selectionStart = newCursorPos;
        textarea.selectionEnd = newCursorPos;

        textarea.focus();

        updatePreview();
        updateInfo();
    } catch (error) {
        showError(error.message);
    }
}

// Show error
function showError(message) {
    const errorDiv = document.getElementById('error-message');
    const errorText = document.getElementById('error-text');
    errorText.textContent = message;
    errorDiv.style.display = 'block';
    
    setTimeout(() => {
        errorDiv.style.display = 'none';
    }, 5000);
}

// Initialize
async function init() {
    try {
        const module = await loadWasmModule();
        MarkdownEditor = module.MarkdownEditor;
        parseMarkdownDocument = module.parseMarkdownDocument;
        
        // Create editor with initial content
        editor = new MarkdownEditor('# Welcome to Proton Pass Markdown Editor!\n\nStart editing to see the magic happen. ✨\n\n## Features\n\n- **Bold** text\n- *Italic* text\n- ~~Strikethrough~~ text\n- Headers (H1-H6)\n- Blockquotes\n- Lists (ordered and unordered)\n- Full undo/redo support\n\n> This is a blockquote! Click the ❝ Quote button to toggle blockquotes on any line.\n\n## Try it out!\n\nSelect some text and click the formatting buttons above.');
        
        // Set initial content in textarea
        const textarea = document.getElementById('editor');
        textarea.value = editor.getText();
        
        // Update preview
        updatePreview();
        updateInfo();
        
        // Hide loading
        document.getElementById('loading').style.display = 'none';
        
        // Setup event listeners
        setupEventListeners();
        
    } catch (error) {
        console.error('Failed to initialize:', error);
        const loading = document.getElementById('loading');
        const wrapper = document.createElement('div');
        wrapper.style.textAlign = 'center';
        wrapper.style.color = '#ff4444';

        const heading = document.createElement('h2');
        heading.textContent = 'Failed to Load';

        const message = document.createElement('p');
        message.textContent = error.message;

        const hint = document.createElement('p');
        hint.style.marginTop = '20px';
        hint.style.color = '#b0b0b0';
        hint.textContent = "Make sure you've built the WASM module:";

        const command = document.createElement('pre');
        command.style.background = '#2a2a2a';
        command.style.padding = '15px';
        command.style.borderRadius = '6px';
        command.style.display = 'inline-block';
        command.style.textAlign = 'left';
        command.style.marginTop = '10px';
        command.textContent = 'cd test-markdown-website\n./setup.sh';

        wrapper.appendChild(heading);
        wrapper.appendChild(message);
        wrapper.appendChild(hint);
        wrapper.appendChild(command);
        loading.replaceChildren(wrapper);
    }
}

export function renderMarkdownDocument(container, markdownDocument) {
    const nodesById = new Map(markdownDocument.nodes.map(node => [node.id, node]));
    const fragment = document.createDocumentFragment();

    markdownDocument.root.forEach(nodeId => {
        const node = nodesById.get(nodeId);
        if (!node) return;

        fragment.appendChild(renderMarkdownNode(node, nodesById));
    });

    container.replaceChildren(fragment);
}

export function renderMarkdownNode(node, nodesById) {
    const children = () => node.children
        .map(childId => nodesById.get(childId))
        .filter(Boolean)
        .map(child => renderMarkdownNode(child, nodesById));

    switch (node.kind) {
        case 'paragraph':
            return elementWithChildren('p', children());
        case 'heading':
            return elementWithChildren(`h${Math.min(Math.max(node.level || 1, 1), 6)}`, children());
        case 'text':
            return document.createTextNode(node.text || '');
        case 'strong':
            return elementWithChildren('strong', children());
        case 'emphasis':
            return elementWithChildren('em', children());
        case 'strikethrough':
            return elementWithChildren('s', children());
        case 'inlineCode': {
            const code = document.createElement('code');
            code.textContent = node.text || '';
            return code;
        }
        case 'codeBlock': {
            const pre = document.createElement('pre');
            const code = document.createElement('code');
            if (node.language) {
                code.dataset.language = node.language;
            }
            code.textContent = node.text || '';
            pre.appendChild(code);
            return pre;
        }
        case 'link': {
            const safeLink = node.safeLink || node.safe_link;
            const unsafeLink = node.unsafeLink || node.unsafe_link;

            if (!safeLink) {
                const span = elementWithChildren('span', children());
                span.className = 'unsafe-link';
                span.title = unsafeLink ? `Unsafe link: ${unsafeLink.reason}` : 'Unsafe link';
                return span;
            }

            const anchor = elementWithChildren('a', children());
            anchor.href = safeLink.href;
            anchor.rel = 'noopener noreferrer';
            return anchor;
        }
        case 'blockquote':
            return elementWithChildren('blockquote', children());
        case 'orderedList': {
            const list = elementWithChildren('ol', children());
            if (node.startNumber && node.startNumber !== 1) {
                list.start = node.startNumber;
            }
            return list;
        }
        case 'unorderedList':
            return elementWithChildren('ul', children());
        case 'listItem':
            return elementWithChildren('li', children());
        default: {
            const span = document.createElement('span');
            span.textContent = node.text || '';
            return span;
        }
    }
}

export function elementWithChildren(tagName, childNodes) {
    const element = document.createElement(tagName);
    childNodes.forEach(child => element.appendChild(child));
    return element;
}

// Setup event listeners
function setupEventListeners() {
    const textarea = document.getElementById('editor');
    const overlay = document.getElementById('styled-overlay');

    // Editor events - update immediately on any change
    textarea.addEventListener('input', updateEditor);
    textarea.addEventListener('paste', () => setTimeout(updateEditor, 0));
    textarea.addEventListener('cut', () => setTimeout(updateEditor, 0));
    textarea.addEventListener('selectionchange', updateInfo);
    textarea.addEventListener('keyup', updateCursorInfo);
    textarea.addEventListener('mouseup', updateCursorInfo);

    // Sync scroll between textarea and overlay
    textarea.addEventListener('scroll', () => {
        overlay.scrollTop = textarea.scrollTop;
        overlay.scrollLeft = textarea.scrollLeft;
    });

    // Keyboard shortcuts + immediate updates for certain keys
    textarea.addEventListener('keydown', (e) => {
        // Handle Enter key for smart list continuation
        if (e.key === 'Enter' && !e.shiftKey && !e.ctrlKey && !e.metaKey) {
            e.preventDefault();

            try {
                // Use smart newline insertion from Rust
                editor.insertNewline();

                // Sync the text and cursor back to textarea
                const newText = editor.getText();
                const cursorPos = editor.getCursor();  // Now returns UTF-16 offset directly

                textarea.value = newText;

                // Rust library now returns UTF-16 offsets (which JS uses natively)
                textarea.setSelectionRange(cursorPos, cursorPos);

                // Update displays
                updatePreview();
                updateInfo();
            } catch (e) {
                console.error('Failed to insert newline:', e);
                // Fallback: let default behavior happen
                textarea.value = textarea.value.substring(0, textarea.selectionStart) + '\n' +
                                 textarea.value.substring(textarea.selectionEnd);
                textarea.selectionStart = textarea.selectionEnd = textarea.selectionStart + 1;
            }
            return;
        }

        // Handle keyboard shortcuts
        if (e.ctrlKey || e.metaKey) {
            switch (e.key.toLowerCase()) {
                case 'b':
                    e.preventDefault();
                    applyOperation('bold');
                    break;
                case 'i':
                    e.preventDefault();
                    applyOperation('italic');
                    break;
                case 'z':
                    if (e.shiftKey) {
                        e.preventDefault();
                        handleRedo();
                    } else {
                        e.preventDefault();
                        handleUndo();
                    }
                    break;
                case 'y':
                    e.preventDefault();
                    handleRedo();
                    break;
            }
        }
    });
    
    // Toolbar buttons
    document.getElementById('btn-bold').addEventListener('click', () => applyOperation('bold'));
    document.getElementById('btn-italic').addEventListener('click', () => applyOperation('italic'));
    document.getElementById('btn-strikethrough').addEventListener('click', () => applyOperation('strikethrough'));
    document.getElementById('btn-h1').addEventListener('click', () => applyOperation('header1'));
    document.getElementById('btn-h2').addEventListener('click', () => applyOperation('header2'));
    document.getElementById('btn-h3').addEventListener('click', () => applyOperation('header3'));
    document.getElementById('btn-blockquote').addEventListener('click', () => applyOperation('blockquote'));
    document.getElementById('btn-ul').addEventListener('click', () => applyOperation('createUnorderedList'));
    document.getElementById('btn-ol').addEventListener('click', () => applyOperation('createOrderedList'));
    document.getElementById('btn-indent').addEventListener('click', () => applyOperation('indentList'));
    document.getElementById('btn-unindent').addEventListener('click', () => applyOperation('unindentList'));
    document.getElementById('btn-undo').addEventListener('click', handleUndo);
    document.getElementById('btn-redo').addEventListener('click', handleRedo);
    document.getElementById('btn-clear').addEventListener('click', handleClear);
    
    // Toggle view
    document.getElementById('toggle-view').addEventListener('change', (e) => {
        const preview = document.getElementById('preview');
        const rawHtml = document.getElementById('raw-html');
        
        if (e.target.checked) {
            preview.classList.add('active');
            rawHtml.classList.remove('active');
        } else {
            preview.classList.remove('active');
            rawHtml.classList.add('active');
        }
    });
}

// Handle undo
function handleUndo() {
    if (!editor || !editor.canUndo()) return;

    editor.undo();

    const textarea = document.getElementById('editor');
    textarea.value = editor.getText();

    // Update cursor
    // Rust library returns UTF-16 offset directly, no conversion needed
    const cursorPos = editor.getCursor();
    textarea.selectionStart = cursorPos;
    textarea.selectionEnd = cursorPos;

    textarea.focus();
    updatePreview();
    updateInfo();
}

// Handle redo
function handleRedo() {
    if (!editor || !editor.canRedo()) return;

    editor.redo();

    const textarea = document.getElementById('editor');
    textarea.value = editor.getText();

    // Update cursor
    // Rust library returns UTF-16 offset directly, no conversion needed
    const cursorPos = editor.getCursor();
    textarea.selectionStart = cursorPos;
    textarea.selectionEnd = cursorPos;

    textarea.focus();
    updatePreview();
    updateInfo();
}

// Handle clear
function handleClear() {
    if (!confirm('Are you sure you want to clear all content?')) return;
    
    if (!editor) return;
    
    editor.setText('');
    
    const textarea = document.getElementById('editor');
    textarea.value = '';
    textarea.focus();
    
    updatePreview();
    updateInfo();
}

// Initialize on load
if (typeof window !== 'undefined') {
    window.addEventListener('DOMContentLoaded', init);
}
