[package]
name = "proton-pass-types"
version = "1.7.0"
edition = "2021"

[lib]
doctest = false

[features]
default = []
uniffi = ["dep:uniffi"]
wasm = ["dep:tsify", "dep:wasm-bindgen"]

[dependencies]
proton-pass-derive = { path = "../proton-pass-derive" }

uniffi = { workspace = true, optional = true }
tsify = { workspace = true, optional = true }
wasm-bindgen = { workspace = true, optional = true }

anyhow = "1.0"
protobuf = "3.7"
serde = { workspace = true }
uuid = { version = "1.23", features = ["v4", "js"] }

[build-dependencies]
protobuf-codegen = "3.7"
protoc-bin-vendored = "3.2.0"
